services:
  - name: backend
    type: web
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
        
  - name: frontend
    type: web
    runtime: node
    region: oregon
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    rootDir: app
    envVars:
      - key: NODE_ENV
        value: production
